library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- This is a simple top-level module that implements a UART message loopback. It receives messages of N_BYTES over UART,
-- and then retransmits the same message back over UART after a configurable number of cycles to simulate application processing time.
-- It can be used to test the uart_msg_rx and uart_msg_tx modules together, as well as to measure the latency of receiving and transmitting messages.
entity uart_msg_loopback_top is
    generic (
        CLK_FREQ          : integer := 100_000_000;     -- machine clock frequency (Hz)
        BAUD_RATE         : integer := 115200;          -- default baud rate (bits per second)
        N_BYTES           : positive := 8;              -- number of bytes in a complete message
        APP_LATENCY_CYCLES : natural := 0               -- number of clock cycles to wait between receiving a message and starting to transmit the response
    );
    port (
        Clk        : in  std_logic;
        Rst        : in  std_logic;         -- active low
        uart_rx_i  : in  std_logic;         -- UART receive line (idle high)
        uart_tx_o  : out std_logic;         -- UART transmit line (idle high)

        bench_req_data   : out std_logic_vector(N_BYTES*8-1 downto 0);  -- output for the received message data
        bench_req_valid  : out std_logic;                               -- high for one cycle when a new message has been received and is valid on bench_req_data
        bench_rx_valid   : out std_logic;                               -- high for one cycle when a new byte has been received from uart_rx and is valid on rx_data_s (for testing uart_msg_rx independently)
        bench_rsp_data   : out std_logic_vector(N_BYTES*8-1 downto 0);  -- output for the message data that is being transmitted in response
        bench_rsp_valid  : out std_logic;                               -- high for one cycle when we start transmitting a message in response (when tx_start_s is pulsed) - used for testing uart_msg_tx independently
        bench_app_cycles : out std_logic_vector(31 downto 0)            -- output for the number of cycles we spent in the APP_RUN state, which simulates application processing time.
    );
end uart_msg_loopback_top;

architecture Behavioral of uart_msg_loopback_top is
    signal baud_tick_s : std_logic := '0';          -- signal for the baud tick generated by the baud_gen module, used to time the UART transmission

    -- Signals to interface with the uart_msg_rx and uart_msg_tx modules
    signal rx_msg_s   : std_logic_vector(N_BYTES*8-1 downto 0) := (others => '0');
    signal rx_valid_s : std_logic := '0';
    signal rx_busy_s  : std_logic := '0';

    signal tx_start_s : std_logic := '0';
    signal tx_busy_s  : std_logic := '0';
    signal tx_msg_s   : std_logic_vector(N_BYTES*8-1 downto 0) := (others => '0');

    -- State machine states for controlling the loopback behavior.
    type state_t is (IDLE, REQ_PULSE, APP_RUN, RESP_PULSE, TX_WAIT);
    signal state : state_t := IDLE;
    -- Counter and register signals for simulating application processing time in the APP_RUN state.
    signal app_count : natural range 0 to APP_LATENCY_CYCLES := 0;
    signal app_cycles_s : unsigned(31 downto 0) := (others => '0');
    -- Signal to latch the received message when we get a valid signal from uart_msg_rx, so that we can use it for both the bench_req_data output and for loading into the uart_msg_tx for transmission.
    signal rx_msg_latched_s : std_logic_vector(N_BYTES*8-1 downto 0) := (others => '0');

begin
    -- Instantiate the baud_gen module to generate the baud_tick signal based on the specified clock frequency and baud rate. 
    baud_inst : entity work.baud_gen
        generic map (
            CLK_FREQ  => CLK_FREQ,
            BAUD_RATE => BAUD_RATE
        )
        port map (
            Clk       => Clk,
            Rst       => Rst,
            baud_tick => baud_tick_s
        );
    -- Instantiate the uart_msg_rx module to handle the reception of messages over UART.
    rx_inst : entity work.uart_msg_rx
        generic map (
            CLK_FREQ  => CLK_FREQ,
            BAUD_RATE => BAUD_RATE,
            N_BYTES   => N_BYTES
        )
        port map (
            Clk       => Clk,
            Rst       => Rst,
            uart_rx_i => uart_rx_i,
            msg_data  => rx_msg_s,
            msg_valid => rx_valid_s,
            busy      => rx_busy_s
        );
    -- Instantiate the uart_msg_tx module to handle the transmission of messages over UART.
    tx_inst : entity work.uart_msg_tx
        generic map (
            N_BYTES => N_BYTES
        )
        port map (
            Clk       => Clk,
            Rst       => Rst,
            baud_tick => baud_tick_s,
            msg_start => tx_start_s,
            msg_data  => tx_msg_s,
            busy      => tx_busy_s,
            uart_tx_o => uart_tx_o
        );

    process(Clk)
    begin
        if rising_edge(Clk) then
            -- reset is active LOW, reset state machine and outputs to idle conditions
            if Rst = '0' then
                state <= IDLE;
                app_count <= 0;
                app_cycles_s <= (others => '0');
                tx_start_s <= '0';
                tx_msg_s <= (others => '0');
                rx_msg_latched_s <= (others => '0');
                bench_req_data <= (others => '0');
                bench_req_valid <= '0';
                bench_rx_valid <= '0';
                bench_rsp_data <= (others => '0');
                bench_rsp_valid <= '0';
            else
                tx_start_s <= '0';
                bench_req_valid <= '0';
                bench_rx_valid <= rx_valid_s;
                bench_rsp_valid <= '0';

                case state is
                    -- In IDLE state, we wait for a valid signal from uart_msg_rx to indicate that a new message has been received and is available on rx_msg_s.
                    when IDLE =>
                        if rx_valid_s = '1' then
                            rx_msg_latched_s <= rx_msg_s;   -- latch the received message so that we can use it.
                            app_count <= 0;                 -- start the application processing counter
                            state <= REQ_PULSE;
                        end if;

                    -- In REQ_PULSE state, we will pulse the bench_req_valid signal for one cycle to indicate that a new message has been received and is valid on bench_req_data, 
                    -- and we will also load the received message into tx_msg_s to prepare for transmission after the APP_RUN state.
                    when REQ_PULSE =>
                        bench_req_data <= rx_msg_latched_s;
                        bench_req_valid <= '1';
                        tx_msg_s <= rx_msg_latched_s;
                        state <= APP_RUN;

                    -- In APP_RUN state, we simply wait for a specified number of cycles (APP_LATENCY_CYCLES) to simulate application processing time before we start transmitting the response message.
                    when APP_RUN =>
                        if app_count = APP_LATENCY_CYCLES then
                            app_cycles_s <= to_unsigned(app_count, 32);
                            state <= RESP_PULSE;
                        else
                            app_count <= app_count + 1;
                        end if;

                    -- In RESP_PULSE state, we will pulse the bench_rsp_valid signal for one cycle to indicate that we are starting to transmit a message in response,
                    -- and we will pulse tx_start_s to start the transmission of the message loaded in tx_msg_s.
                    when RESP_PULSE =>
                        bench_rsp_data <= tx_msg_s;
                        bench_rsp_valid <= '1';
                        tx_start_s <= '1';
                        state <= TX_WAIT;

                    -- In TX_WAIT state, we wait for the uart_msg_tx module to finish transmitting the message. 
                    -- We know it's finished when tx_busy_s goes low, at which point we can go back to IDLE and wait for the next message.
                    when TX_WAIT =>
                        if tx_busy_s = '0' then
                            state <= IDLE;
                        end if;
                end case;
            end if;
        end if;
    end process;

    -- For testing purposes, we will also output the received message data and the response message data on bench outputs, along with valid signals to indicate when they are valid.
    bench_app_cycles <= std_logic_vector(app_cycles_s);

end Behavioral;